firstsite/firstsite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import (
    SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView,
    )

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/docs/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/docs/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    
    path('api/', include('myapiapp.urls')),
    path('shop_api/', include('shopapp.api_urls')),
    
    
    path('blog/', include('blogapp.urls')),
    
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap")
    
]

urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
    path('myauth/', include('myauth.urls')),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    
    # urlpatterns.extend(
    #     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # )
    
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

firstsite/myauth/urls.py
from django.urls import path
from .views import (
    pre_logout_view,
    set_cookie_view, 
    get_cookie_view,
    set_session_view,
    get_session_view,
    
    MyLogoutView,
    MyLoginView,
    
    AboutMeView,
    RegisterView,
    
    UserListView,
    ProfileDetailsView,
    ProfileUpdateView,
    
    FooBarView,
    
    HelloView,
)

app_name = "myauth"

urlpatterns = [
    path("login/", 
         MyLoginView.as_view(template_name="myauth/login.html"),
         name="login"),
   
    path("prelogout/<str:username>/", pre_logout_view, name="pre_logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
         
    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/set", set_session_view, name="session-set"),
    path("session/get", get_session_view, name="session-get"),
    
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    
    path("users/", UserListView.as_view(), name="users-list"),
    path("profile/<int:pk>/details/", ProfileDetailsView.as_view(), name="profile-details"),
    path("profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile-update"),
    
    path("register/", RegisterView.as_view(), name="register"),
    
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
    
    path("hello/", HelloView.as_view(), name="hello"),
    
]

firstsite/shopapp/urls.py
from django.urls import path, include

from .views import (
    ShopIndexView,
    GroupsListView,
    
    ProductDetailsView, 
    ProductListView, 
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    
    OrderListView,
    OrderDetailView,
    OrderCreateView,
    OrderUpdateView,
    OrderDeleteView,
    
    OrderDataExportView,
    OrderDataExportViewById,
    
    UserOrdersListView,
)

from django.views.decorators.cache import cache_page

app_name = "shopapp"


urlpatterns = [
    #path("", cache_page(30)(ShopIndexView.as_view()), name="index"),
    path("", ShopIndexView.as_view(), name="index"),
    path("groups/", GroupsListView.as_view(), name="groups"),
    
    path("products/", ProductListView.as_view(), name="products"),   
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_detail"),   
    path("products/create/", ProductCreateView.as_view() , name="product_create"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view() , name="product_update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view() , name="product_delete"),
    
    path("orders/", OrderListView.as_view(), name="orders"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),   
    
    
    path("orders/create/", OrderCreateView.as_view(), name="order_create"),
    path("orders/<int:pk>/update/", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete/", OrderDeleteView.as_view(), name="order_delete"),
    
    path("orders/export/", OrderDataExportView.as_view(), name="orders-export"),
    path("orders/export/<int:pk>/user/", OrderDataExportViewById.as_view(), name="orders-export-by-id"),
    
    
    path("orders/user/<int:pk>/", UserOrdersListView.as_view(), name="orders-user"),
    
    
    
]

firstsite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models

def product_preview_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/preview/{filename}".format(
        pk=instance.pk,
        filename=filename,
    )
    
def product_images_directory_path(instance: "Product", filename: str) -> str:
    return "products/product_{pk}/images/{filename}".format(
        pk=instance.product.pk,
        filename=filename,
    )


class CustomProductManager(models.Manager):
    use_for_related_fields = True
    def get_queryset(self):
        return super().get_queryset().filter(archived=False)
    
class Product(models.Model):
    """
    Модель Product.
    
    Объект описывающий товар, который можно приобрести в магазине. (shop)
    
    Посмотреть заказы: :model:`shopapp.Order`
    """
    objects = models.Manager()
    all_objects = CustomProductManager()
   
    class Meta:
        ordering = ["name", "price"]
        base_manager_name = 'objects'
        
    name = models.CharField(max_length=100, db_index=True)
    description = models.TextField(null=False, blank=True, db_index=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    
    # нельзя удалять пользователя при наличии продуктов им внесёнными
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True) 
    
    preview = models.ImageField(null=True, blank=True, upload_to=product_preview_directory_path)
    
    def __str__(self) -> str:
        return f"Product(pk={self.pk}, name={self.name!r})"
    
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField(upload_to=product_images_directory_path)
    description = models.CharField(max_length=200, null=False, blank=True)
    
    
class Order(models.Model):
    """
    Заказы. (покупки)
    
    
    """
    delivery_address = models.TextField(null=False, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    
    products = models.ManyToManyField(Product, related_name="orders")
    
    receipt = models.FileField(null=True, upload_to='orders/receipts')

firstsite/shopapp/views.py
"""
Модуль взаимодействия.

Представлений и orm-моделей бд.

Вот.
"""



from timeit import default_timer
from csv import DictWriter

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.urls import reverse_lazy
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, JsonResponse
from django.views import View
from django.views.generic import (
    #TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from rest_framework.decorators import action
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser

from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter, OrderingFilter
from django_filters.rest_framework import DjangoFilterBackend

from drf_spectacular.utils import extend_schema, OpenApiResponse


from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from django.core.cache import cache

from .models import Product, Order, User, ProductImage
from .forms import ProductForm, OrderForm, GroupForm

from .common import save_csv_products

from .serializers import ProductSerializer, OrderSerializer

import random
import logging

log  = logging.getLogger(__name__)






@extend_schema(description="Product wievs CURD")
class ProductViewSet(ModelViewSet):
    """
    Набор представлений CRUD для Product.
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = [
        "name", 
        "description",
    ]
    filterset_fields = [
        "name",
        "description",
        "price",
        "discount",
        "archived",
    ]
    ordering_fields = [
        "pk",
        "name",
        "price",
        "discount",
    ]
    
    # Это нужно, чтобы в swagger отплевывало надпись ниже
    @extend_schema(
        summary="Get 1 product by ID",
        description="Retrieves **Product**, return 404 if None.",
        responses={
            200: ProductSerializer,
            404: OpenApiResponse(description=" NOT FOUND ")
        }
    )
    def retrieve(self, request, *args, **kwargs):
        return super().retrieve(request, *args, **kwargs)
    
    @action(methods=["get"], detail=False)
    def download_csv(self, request: Request):
        
        response = HttpResponse(content_type="text/csv")
        filename = "products-export.csv"
        response["Content-Disposition"] = f"attachment; filename={filename}"
        
        queryset = self.filter_queryset(self.get_queryset())
        fields = [
        "name",
        "description",
        "price",
        "discount",
        ]
        queryset = queryset.only(*fields)
        writer = DictWriter(response, fieldnames=fields)
        writer.writeheader()
        
        for product in queryset:
            writer.writerow({
                field: getattr(product, field)
                for field in fields
            })    
            
        return response
    
    @action(detail=False, methods=["post"], parser_classes=[MultiPartParser])
    def upload_csv(self, request: Request):
        products = save_csv_products(
            file=request.FILES["file"].file,
            encoding=request.encoding
        )
        serializer = self.get_serializer(products, many=True)
        return Response(serializer.data)
    
    @method_decorator(cache_page(30))
    def list(self, *args, **kwargs):
        print('*'*8, "********************", '*'*8)
        print('*'*8, "FUNC LIST IS EXECUTE", '*'*8)
        print('*'*8, "********************", '*'*8)
        return super().list(*args, **kwargs)
        
    
class OrderViewSet(ModelViewSet):
    queryset = Order.objects.prefetch_related("products").all()
    serializer_class = OrderSerializer
    filter_backends = [
        SearchFilter,
        DjangoFilterBackend,
        OrderingFilter,
    ]
    search_fields = (
            "delivery_address",
            "promocode", 
        )
    filterset_fields = (
            "delivery_address",
            "promocode", 
            "user",
            "products",
            
        )
    ordering_fields = (
            "pk",
            "delivery_address",
            "promocode", 
            "created_at",
        )
    



class ShopIndexView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        tups_of_vals = (
            ('First', 1234),
            ('Second', 4321),
            ('Third', 12345),
        ) if random.randint(0, 1) else ()
        
        context = {
            "time_running": default_timer(),
            "some_list": tups_of_vals,        
            "some_str": "abc\ndef\nghkl",
        }
        log.debug("Products for shop index: %s", tups_of_vals)
        log.info("Rendering shop index")
        
        print('*'*8, '**********************************************', '*'*8)
        print('*'*8, 'SHOP INDEX CONTEXT:', context, '*'*8)
        print('*'*8, '**********************************************', '*'*8)
        
        return render(request, 'shopapp/shop-index.html', context=context)

class GroupsListView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {
            "form": GroupForm(),
            "groups": Group.objects.prefetch_related('permissions').all()
        }
        return render(request, 'shopapp/groups-list.html', context=context)
    
    def post(self, request: HttpRequest) -> HttpResponse:
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()            
        return redirect(request.path)





class OrderListView(LoginRequiredMixin, ListView):
    template_name = "shopapp/orders-list.html"
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )    

class OrderDetailView(PermissionRequiredMixin, DetailView):
    permission_required = "shopapp.view_order"
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )

class OrderCreateView(CreateView):
    model = Order
    fields = (
        "delivery_address", 
        "promocode", 
        "user", 
        "products"
    )
    success_url = reverse_lazy("shopapp:orders")

class OrderUpdateView(UpdateView):
    model = Order
    fields = (
        "delivery_address", 
        "promocode", 
        "user", 
        "products"
    )
    #queryset = model.objects.filter(products__archived=False).prefetch_related()#.all()
    template_name_suffix = "_update_form"
    
    def get_success_url(self): # Для возможности перенаправить по url с индексом pk
        return reverse(
            "shopapp:order_detail",
            kwargs = {"pk": self.object.pk}
        )


class OrderDeleteView(DeleteView):
    model = Order
    success_url = reverse_lazy("shopapp:orders")    



class ProductListView(ListView):
    template_name = "shopapp/products-list.html"
    model = Product
    queryset = Product.all_objects.all() # !!! objects переопределен
    context_object_name = "products"

class ProductDetailsView(DetailView):
    template_name = "shopapp/product_detail.html"
    #model = Product
    queryset = Product.objects.prefetch_related("images")
    fields = "name", "price", "description", "discount", "preview"
    context_object_name = "product"

class ProductCreateView(UserPassesTestMixin, CreateView):
    # создавать только если есть разрешение
    def test_func(self):
        return self.request.user.has_perm('shopapp.add_product') 
    
    # приматывание user к таблице
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.created_by = self.request.user
        return super(ProductCreateView, self).form_valid(form)
    
    model = Product
    fields = "name", "price", "description", "discount", "preview"
    success_url = reverse_lazy("shopapp:products")

class ProductUpdateView(UserPassesTestMixin, UpdateView):
    # изменять только если есть разрешение
    def test_func(self):
        return self.request.user.has_perm('shopapp.change_product') 
    
    model = Product
    #fields = "name", "price", "description", "discount", "preview"
    template_name_suffix = "_update_form"
    #success_url = reverse_lazy("shopapp:products")
    form_class = ProductForm
    
    def get_success_url(self):
        return reverse(
            "shopapp:product_detail",
            kwargs = {"pk": self.object.pk}
        )
        
    def form_valid(self, form):
        # Проверка на наличие разрешения
        obj = form.save(commit=False)
        if self.request.user.is_superuser or (obj.created_by == self.request.user):
            response = super().form_valid(form)
            for image in form.files.getlist("images"):
                ProductImage.objects.create(
                    product=self.object,
                    image=image,
                )
            return response
        #else
        return super(ProductUpdateView, self).form_invalid(form)
        
                

class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products")    

    # Удаление понарошку
    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)





# Задание 19 кэширование в html-шаблоне orders-user-list.html
# http://127.0.0.1:8000/ru/shop/orders/user/1/

class UserOrdersListView(LoginRequiredMixin, ListView):
    
    template_name = "shopapp/orders-user-list.html"
    
    def get_queryset(self):         
        return (

firstsite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
    
<head>
    
    <meta charset="UTF-8">
    <title>
        {% block title %}
        Base Title
        {% endblock %}
    </title>
    <style>
        body { font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 10px }
    </style>

</head>
<body>
    {% block body %}
    Base Body
        
    {% endblock %}
</body>
</html>

firstsite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Groups List' %}
{% endblock %}

{% block body %}
    <h2>{% translate 'Groups' %}:</h2>
    
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% translate 'Create' %}</button>
        </form>
    </div>

    <div>
        {% if not groups %}
        <h2>{% translate 'Groups are empty' %}</h2>
        {% else %}
            {% for group_item in groups %}
                <li>
                    <div>{{group_item.name}}</div>
                        {% for permission in group_item.permissions.all %}
                            <li>{{permission.name}} ({{permission.codename}})</li>
                        {% endfor %}
                    </div>
                </li>
            {% endfor %}
        {% endif %}
    </div>
{% endblock %}

firstsite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Confirm Delete Order' %} {{ object.name }}
{% endblock %}

{% block body %}    
    <h1>{% translate 'ARE YOU SURE?' %}</h1>
    <h2>{% translate 'Order' %}</h2>
    <h1>{{object.name}}</h1>
    <h2>{% translate 'will be deleted' %}</h2>
    <br>
    <div>
        <a href="{% url 'shopapp:order_detail' pk=object.pk %}">{% translate 'Back to Order-details' %}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% translate 'DELETE' %}</button> 
        </form>
    </div>
{% endblock %}

firstsite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Order' %} #{{ object.pk }} {% translate 'details' %}
{% endblock %}

{% block body %}
    <div>
        <h1>{% translate 'Order' %} #{{ object.pk }}</h1>
        <p>{% translate 'Who' %}: {% firstof object.user.first_name object.user.username %}</p>
        <p>{% translate 'Address' %}: {{object.delivery_address}}</p>
        <p>{% translate 'Pcode' %}: {{object.promocode}}</p>
        {% translate 'Products' %}:
        <ul>
            {% for product in object.products.all %}
                <li>{{ product.name }} ... {{ product.price }}</li>
            {% endfor %}
        </ul>
    </div>
    <div>
        <a href="{% url 'shopapp:order_update' pk=order.pk %}"> {% translate 'Update Order Values' %} </a>
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:orders' %}">{% translate 'Back to Orders List' %}</a> 
    </div>
    <br>
    <div>
        <a href="{% url 'shopapp:order_delete' pk=order.pk %}">{% translate 'Delete Order' %}</a>
    </div>
{% endblock %}

firstsite/shopapp/templates/shopapp/order_form.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Create Order' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Create Order' %}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> {% translate 'Add Order' %} </button> 
        </form>
    </div>
    <div>
        <a href ="{% url 'shopapp:orders' %}">{% translate 'Back to Orders' %}</a>
    </div>
{% endblock %}

firstsite/shopapp/templates/shopapp/order_update_form.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
   {% translate 'Update Order'%}
{% endblock %}

{% block body %}
    <h1>{% translate 'Update Order' %}</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% translate 'Update Order' %}</button> 
        </form>
    </div>
    <div>
        <a href ="{% url 'shopapp:orders' %}">{% translate 'Back to Orders' %}</a>
    </div>
{% endblock %}

firstsite/shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Orders List' %}
{% endblock %}

{% block body %}    
    {% for order in object_list %}
    <li>
        <p><a href="{% url 'shopapp:order_detail' pk=order.pk %}">Detais</a></p>
        <p>{% translate 'Who' %}: {% firstof order.user.first_name order.user.username %}</p>
        <p>{% translate 'Address' %}: {{order.delivery_address}}</p>
        <p>{% translate 'Pcode' %}: {{order.promocode}}</p>
        {% translate 'Products' %}:
        <ul>
            {% for product in order.products.all %}
                <li>{{ product.name }} for {{ product.price }}</li>
            {% endfor %}
        </ul>
    </li>
    {% empty %}
        {% translate 'Nothing to show..' %}
    {% endfor %}

    <div>
        <a href ="{% url "shopapp:order_create" %}">
            {% translate 'Create Order' %}
        </a>
    </div>

{% endblock %}

firstsite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
     {% translate 'Confirm Delete' %} {{ object.name }}
{% endblock %}

{% block body %}    
    <h1> {% translate 'ARE YOU SURE?' %}</h1>
    <h2>{% translate 'Product' %}</h2>
    <h1>{{object.name}}</h1>
    <h2>{% translate 'will be deleted' %}</h2>
    <br>
    <div>
        <a href="{% url 'shopapp:product_detail' pk=object.pk %}"
        >{% translate 'Back to Product-details' %}</a>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">{% translate 'DELETE' %}</button> 
        </form>
    </div>
{% endblock %}

firstsite/shopapp/templates/shopapp/product_detail.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
     {% translate 'Product' %} #{{ product.pk }}
{% endblock %}

{% block body %}
     {% translate 'Product' %} <h1> <strong>{{ product.name }}</strong></h1>
    <div>
        <div>{% translate 'Description' %}: <em>{{ product.description }}</em></div>
        <div> {% translate 'Product Price' %}: <em>{{ product.price }}</em></div>
        <div> {% translate 'Discount' %}: <em>{{ product.discount }}</em></div>
        <div> {% translate 'Archived' %}: <em>{{ product.archived }}</em></div>

        {% if product.preview %}
            <img src={{ product.preview.url }} alt={{ product.preview.name }}>
        {% endif %}

        <h3> {% translate 'Images' %}:</h3>
        <div>
            {% for item in product.images.all %}
                <div><img src={{ item.image.url }}></div>
                <div>{{ item.description }}</div>
            {% empty %}
            <div> {% translate 'No Images Uploaded Yet' %}</div>
            {% endfor %}
        </div>


    </div>
    
    {% if perms.shopapp.change_product %}
    <br>
    <div>
        <a href="{% url 'shopapp:product_update' pk=product.pk %}">  {% translate 'Update Values' %} </a>
    </div>
    {% endif %}

    <br>
    <div>
        <a href="{% url 'shopapp:products' %}">  {% translate  'Back to products list' %} </a>
    </div>

    {% if perms.shopapp.delete_product %}
    <br>
    <div>
        <a href="{% url 'shopapp:product_delete' pk=product.pk %}">  {% translate 'Delete Product' %} </a>        
    </div>
    {% endif %}
{% endblock %}

firstsite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
     {% translate 'Create Product' %}
{% endblock %}

{% block body %}
    <h1> {% translate 'Create Product' %}</h1>
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form.as_p }}

            <button type="submit">{% translate  'Create' %} </button> 
        </form>
    </div>
    <div>
        <a href ="{% url 'shopapp:products' %}">
             {% translate 'Back to Products' %}
        </a>
    </div>
{% endblock %}

firstsite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
     {% translate 'Update' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Update Product Values' %}</h1>
    <div>
        <form method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit"> {% translate 'Update' %}</button> 
        </form>
    </div>
    
    <div>
        <a href ="{% url 'shopapp:product_detail' pk=object.pk %}"> {% translate 'Back to Product' %} #{{ object.pk }}</a>
    </div>
{% endblock %}

firstsite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% load i18n %}

{% block title %}
    {% translate 'Products List' %}
{% endblock %}

{% block body %}
    <h1>{% translate 'Products' %}:</h1>

    {% blocktranslate count product_count=products|length %}
        Only one product

        {% plural %}
        There are {{product_count}} products
    {% endblocktranslate %}



    {% for product in products %}
    <li>
        <p><a href="{% url 'shopapp:product_detail' pk=product.pk %}"
            >{% translate 'Name' context 'product_name' %}: {{product.name}}</a></p>
        <p>{% translate 'Price' %}: {{product.price}}</p>
        {% translate 'no_discount' as no_discount %}
        <p>{% translate 'Discount' %}: {% firstof product.discount no_discount %}</p>

        {% if product.preview %}
            <img src={{ product.preview.url }} alt={{ product.preview.name }}>
        {% endif %}
    </li>
    {% empty %}
        {% translate 'Nothing to show..' %}
    {% endfor %}
   

{% if perms.shopapp.add_product %}
    <div>    
        <h1>
        <a href ="{% url "shopapp:product_create" %}">
            {% translate 'Create Product' %}
        </a>
    </h1>
    </div>
{% endif %}

{% endblock %}

firstsite/shopapp/templates/shopapp/products_changelist.html
{% extends 'admin/change_list.html' %}


{% block object-tools-items %}
{% load admin_urls %} 
<li>
    <a href="{% url 'admin:import_products_csv' %}" class="addlink">
        Import CSV
    </a>
</li>
{{ block.super }}
{% endblock %}

firstsite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% load cache %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}

<div>
    <ul>
        {% for some_item, some_value in some_list %}
        <li>{{ some_item }} <> {{ some_value }}</li>
        
            {% if some_item|length == 6 %}
            <span>* * * * * * *</span>
            {% endif %}

        {% empty %}
        Nothing to show..
        {% endfor %}
    </ul>
</div>

<div>
    {{some_str|linenumbers|linebreaks|title}}

    <table cellspacing="10" border="2">
        {% for row_num in '123' %}
        <tr>
            {% for col_num in '1234' %}

            <td>{{col_num}} | {{row_num}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
</div>


<div>
    Time running: {{ time_running }}
</div>

{% cache 10 some_key_for_cache %}
<div>
    {% lorem 3 p %}
</div>
{% endcache %}

{% endblock %}