firstsite/firstsite/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from django.conf.urls.i18n import i18n_patterns

from drf_spectacular.views import (
    SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView,
    )

from django.contrib.sitemaps.views import sitemap
from .sitemaps import sitemaps

urlpatterns = [
    path('admin/docs/', include('django.contrib.admindocs.urls')),
    
    path('admin/', admin.site.urls),
    path('req/', include('requestdataapp.urls')),
    
    path('api/schema/', SpectacularAPIView.as_view(), name="schema"),
    path('api/docs/schema/swagger', SpectacularSwaggerView.as_view(url_name='schema'), name="swagger"),
    path('api/docs/schema/redoc', SpectacularRedocView.as_view(url_name='schema'), name="redoc"),
    
    path('api/', include('myapiapp.urls')),
    path('shop_api/', include('shopapp.api_urls')),
    
    
    path('blog/', include('blogapp.urls')),
    
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap")
    
]

urlpatterns += i18n_patterns(
    path('shop/', include('shopapp.urls')),
    path('myauth/', include('myauth.urls')),
)


if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )
    
    # urlpatterns.extend(
    #     static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # )
    
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls"))
    )

firstsite/myauth/urls.py
from django.urls import path
from .views import (
    pre_logout_view,
    set_cookie_view, 
    get_cookie_view,
    set_session_view,
    get_session_view,
    
    MyLogoutView,
    MyLoginView,
    
    AboutMeView,
    RegisterView,
    
    UserListView,
    ProfileDetailsView,
    ProfileUpdateView,
    
    FooBarView,
    
    HelloView,
)

app_name = "myauth"

urlpatterns = [
    path("login/", 
         MyLoginView.as_view(template_name="myauth/login.html"),
         name="login"),
   
    path("prelogout/<str:username>/", pre_logout_view, name="pre_logout"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
         
    path("cookie/get", get_cookie_view, name="cookie-get"),
    path("cookie/set", set_cookie_view, name="cookie-set"),
    path("session/set", set_session_view, name="session-set"),
    path("session/get", get_session_view, name="session-get"),
    
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    
    path("users/", UserListView.as_view(), name="users-list"),
    path("profile/<int:pk>/details/", ProfileDetailsView.as_view(), name="profile-details"),
    path("profile/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile-update"),
    
    path("register/", RegisterView.as_view(), name="register"),
    
    path("foo-bar/", FooBarView.as_view(), name="foo-bar"),
    
    path("hello/", HelloView.as_view(), name="hello"),
    
]

firstsite/myauth/models.py
from django.contrib.auth.models import User
from django.db import models


def profile_avatar_directory_path(instance: "Profile", filename: str) -> str:
    return "users/user_{pk}/avatar/{filename}".format(
        pk=instance.pk,         
        #pk=instance.user.pk, # вроде как 1-1, pk = user.pk 
        
        filename=filename,
    )


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    agreement_accepted = models.BooleanField(default=False)
    
    avatar = models.ImageField(null=True, blank=True, upload_to=profile_avatar_directory_path)
    

firstsite/myauth/forms.py
from django import forms
from .models import Profile, User

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        queryset = model.objects.prefetch_related('users').all()
        fields = ('user',  'bio', 'avatar',)

firstsite/myauth/views.py
from typing import Optional, Any
from django.shortcuts import render, redirect, reverse

from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth import authenticate, login, logout
from django.http import HttpRequest, HttpResponse, JsonResponse

from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView, LoginView 
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import TemplateView, CreateView, View, UpdateView, DetailView, ListView, FormView

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User, Permission

from django.utils.translation import gettext_lazy as _, ngettext

from django.views.decorators.cache import cache_page


from .models import Profile

from .forms import UpdateProfileForm

from random import random    

class AboutMeView(TemplateView):
    template_name = "myauth/about-me.html"



class UserListView(ListView):
    template_name = "myauth/users-list.html"
    model = Profile
    queryset = Profile.objects.all() # !!! objects переопределен
    context_object_name = "all_users"

class ProfileDetailsView(DetailView):
    template_name = "myauth/profile_detail.html"
    model = Profile
    
    
    
class ProfileUpdateView(UserPassesTestMixin, UpdateView):
    # изменять только если есть разрешение
    def test_func(self):
        user = self.request.user
        return user.is_staff or user.has_perm('myauth.change_profile') 
    
    template_name = "myauth/form_profile_update.html"
    model = Profile
    queryset = (
        Profile.objects
        .select_related("user")
    )
    fields = ('user','bio', 'avatar',)
   
    
    def get_success_url(self):
        return reverse(
            "myauth:profile-details",
            kwargs = {"pk": self.object.pk})

    def form_valid(self, form):
        # Проверка на наличие разрешения
        obj = form.save(commit=False)
        if self.request.user.is_superuser or (obj.user == self.request.user):
            print("Data were change")
            return super(ProfileUpdateView, self).form_valid(form)
        #else
        print("Data were not change")
        return super(ProfileUpdateView, self).form_invalid(form)



      
    
class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "myauth/register.html"
    success_url = reverse_lazy("myauth:about-me")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        Profile.objects.create(user=self.object)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(
            self.request,
            username=username,
            password=password
        )
        content_type = ContentType.objects.get_for_model(Profile)
        profile_permission = Permission.objects.filter(content_type=content_type)
        for perm in profile_permission:
            user.user_permissions.add(perm)

        
        login(request=self.request, user=user)        
        return response


class MyLoginView(LoginView):
    def get(self, request: HttpRequest) -> HttpResponse:
        if request.method == "GET":
            context = {}
            if request.user.is_authenticated:                
                context = {"user": request.user }
            #else
            return render(request, 'myauth/login.html', context=context)
        #else
        username = request.POST["username"]
        password = request.POST["password"]
        
        user = authenticate(request, username=username, password=password)
    
        if user is not None:
            login(request, user)
            return redirect("/admin/")
        #else
        return render(request, "myauth/login.html", context={"error": "Invalid login data"})

class MyLogoutView(LogoutView):
    next_page = reverse_lazy("myauth:login")

def pre_logout_view(request: HttpRequest, username: Optional[str]=None) -> HttpResponse:
    context = {"username": username}
    return render(request, "myauth/logout.html",context=context)



@user_passes_test(lambda u:u.is_superuser)        
def set_cookie_view(request: HttpRequest) -> HttpResponse:
    response = HttpResponse("Cookie set")
    response.set_cookie("cheese", "jazz", max_age=3600)
    return response

@cache_page(30)
@permission_required("myauth.view_profile")
def get_cookie_view(request: HttpRequest) -> HttpResponse:
    value = request.COOKIES.get("cheese", "cheese not found")
    return HttpResponse(f"Cookies Values: '{value}   {random()}'")

def set_session_view(request: HttpRequest) -> HttpResponse:
    request.session["some_session_key"] = "some_session_value"
    return HttpResponse("Session set")

@login_required
def get_session_view(request: HttpRequest) -> HttpResponse:
    value = request.session.get("some_session_key", "key_not_found")
    return HttpResponse(f"Session values = '{value}'")


class FooBarView(View):
    def get(self, request: HttpRequest) -> JsonResponse:
        return JsonResponse({"some_key": "some_value", "3": 5})
    
    
class HelloView(View):
    wlcm_msg = _("welcome hello world")
    def get(self, request: HttpRequest) -> HttpResponse:
        items_str = request.GET.get("items") or 0
        items_int = int(items_str)
        products_line = ngettext(
            "one product",
            "{count} products",
            items_int
        )
        products_line = products_line.format(count=items_int)
        return HttpResponse(f"<h1>{self.wlcm_msg}</h1> <h2>{products_line}</h2>")

firstsite/myauth/templates/myauth/about-me.html
{% extends 'myauth/base.html' %}
{% load cache %}

{% block title %}
  User info
{% endblock %}

{% block body %}

    <h1>User info</h1>
    <h1>SoME VALUE :  {% now "u" %}</h1>
    {% if user.is_authenticated %}
    {% cache 300 userinfo user.username %}
    <h1>SOME VALUE FOR CURRENT USER :  {% now "u" %}</h1>
        <h2>Details:</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Last name: {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
        <p>Biograpy: {{ user.profile.bio }}</p>
        {% if user.profile.avatar %}
            <img src={{ user.profile.avatar.url }} alt={{ user.profile.avatar.name }}>
        {% endif %}
        <br>
        <div>
            <a href="{% url 'myauth:profile-update' pk=user.pk %}"> Update profile </a>
        </div>
    {% endcache %}    
    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}

    <br>
    <p><a href="{% url 'myauth:users-list' %}" > ALL Users </a></p>

    {% if user and user.username %}
    <br>
    <p><a href="{% url 'myauth:pre_logout' user.username %}" >{{user.username}} logout</a></p>
    {% endif %}

{% endblock %}

firstsite/myauth/templates/myauth/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>
    <style>
        body { font-family: Arial, 'Helvetica Neue', Helvetica, sans-serif; font-size: 10px }
    </style>

</head>
<body>
    {% block body %}
        Base Body
    {% endblock %}
</body>
</html>

firstsite/myauth/templates/myauth/form_profile_update.html
{% extends 'myauth/base.html' %}

{% block title %}
   Update Profile
{% endblock %}

{% block body %}
    <h1>Update Profile</h1>
    <div>
        <form method="post"  enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            {% comment %} <p>Username: {{ profile.user.username }}</p>
            <div>
            <label for="profile.user.first_name">First name: </label>
            <input type="text" id="profile.user.first_name" name="profile.user.first_name" required value="{{profile.user.first_name}}">
            </div>

            <div>
            <label for="profile.user.last_name">Last name:</label>
            <input type="text" id="profile.user.last_name" name="profile.user.last_name" required value="{{profile.user.last_name}}">
            </div>

            <div>
            <label for="profile.user.email">Email:</label>
            <input type="text" id="profile.user.email" name="profile.user.email" required value="{{profile.user.email}}">
            </div>

            <div>
            <label for="profile.bio">Biography:</label>
            <textarea  id="profile.bio" name="profile.bio" required value="{{profile.bio}}"></textarea>
            </div>
            
            <div>
            <label for="profile.avatar">Email:</label>
            <input type="text" id="profile.avatar" name="profile.avatar" required value="{{profile.avatar.url}}">
            </div>
             {% endcomment %}
            <div>
            <button type="submit">Update Profile</button> 
            </div>
        </form>
    </div>
    
{% endblock %}

firstsite/myauth/templates/myauth/login.html
{% extends 'myauth/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}

        {% comment %} {{ form.as_p }} {% endcomment %}

        {% if error %}
        <p style="color: red">
            {{error}}
        </p>      


        {% endif %}
        
        <p>
            <label for="username">User Name:</label>
            <input type="text" id="username" name="username" required value="{{user.username}}">
        </p>
        <p>
            <label for="password">User Password:</label>
            <input type="password" id="password" name="password" required">
        </p>
        
        <button type="submit">Login</button>
    </form> 
    {% if user and user.username %}
    <br>
    <p><a href="/admin/">log as {{user.username}}</a></p>   
    <br><br>
    <p><a href="{% url 'myauth:pre_logout' user.username %}" >{{user.username}} logout</a></p>

    {% else %}
    <br>
    <p><a href="{% url 'myauth:register' %}"> Register </a></p>
    {% endif %}
    
{% endblock %}

firstsite/myauth/templates/myauth/logout.html
{% extends 'myauth/base.html' %}

{% block title %}
    Logout
{% endblock %}

{% block body %}
<form method="post" action="{% url 'myauth:logout' %}">
    {% csrf_token %}
    <label> user '{{ username }}' please confirm your logout:</label>
    <button type="submit">Confirm</button>
</form>
{% endblock %}

firstsite/myauth/templates/myauth/profile_detail.html
{% extends 'myauth/base.html' %}

{% block title %}
  User info Profile
{% endblock %}

{% block body %}

    <h1>User info</h1>
    {% if profile %}
        <h2>Details:</h2>
        <p>Username: {{ profile.user.username }}</p>
        <p>First name: {{ profile.user.first_name }}</p>
        <p>Last name: {{ profile.user.last_name }}</p>
        <p>Email: {{ profile.user.email }}</p>
        <p>Biograpy: {{ profile.bio }}</p>
        {% if profile.avatar %}
            <img src={{ profile.avatar.url }} alt={{ profile.avatar.name }}>
        {% endif %}

        {% if user.is_authenticated and user == profile.user %}
        <br>
        <div> 
            <a href="{% url 'myauth:profile-update' pk=user.pk %}"> Update profile </a>
        </div>
        {% endif %}

    {% else %}
        <h2>User is anonymous</h2>
    {% endif %}

    <br>
    <p><a href="{% url 'myauth:users-list' %}" > ALL Users </a></p>

    {% if user and user.username %}
    <br>
    <p><a href="{% url 'myauth:pre_logout' user.username %}" >{{user.username}} logout</a></p>
    {% endif %}

{% endblock %}

firstsite/myauth/templates/myauth/register.html
{% extends 'myauth/base.html' %}

{% block title %}
  Register
{% endblock %}

{% block body %}
    <h1>Register</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
    


{% endblock %}

firstsite/myauth/templates/myauth/users-list.html
{% extends 'myauth/base.html' %}

{% block title %}
    Users List
{% endblock %}

{% block body %}
    {% for some_user in all_users %}
    <li>
        <p><a href="{% url 'myauth:profile-details' pk=some_user.user.pk %}">Name: {{some_user.user.username}}</a></p>

        {% if some_user.avatar %}
            <img src={{ some_user.avatar.url }} alt={{ some_user.avatar.name }}>
        {% endif %}
    </li>
    {% empty %}
        Nothing to show..
    {% endfor %}
{% endblock %}